init:
  - git config --global core.autocrlf true

version: '{branch}-{build}'

image: Visual Studio 2017

skip_tags: true

configuration: Release
platform: Any CPU

shallow_clone: false

environment:
  COVERALLS_REPO_TOKEN:
    secure: CbB+HqPrseFu6L/FGrJZf4uTUojOk+t0LuSAV6V5zHitbMwHr+yYuqh5ojlyhC1L

before_build:
- cmd: >-
    git submodule update --init --recursive
    
    _build\version.bat
    
    _build\restore.bat Configgy

build_script:
- cmd: _build\build.bat Configgy

test_script:
- cmd: _build\test.bat Configgy

after_test:
- cmd: _build\package.bat Configgy netcoreapp2.0

artifacts:
- path: '*.nupkg'
  name: Nuget Package

deploy:
- provider: NuGet
  api_key:
    secure: P2oh37pn3l7Tp9qTP87aOB0GFxg8WnlFyV8n3p1eqMS5aUVur1Yg3xQ2inbIDOCr
  skip_symbols: false
  on:
    branch: master
